language: go

sudo: false

go: master

before_install:
  - go get github.com/WindomZ/grequests
  - go get github.com/WindomZ/go-commander
  - go get github.com/WindomZ/go-develop-kit/path
  - go get github.com/PuerkitoBio/goquery
  - go get gopkg.in/cheggaaa/pb.v1
  - go get github.com/WindomZ/testify/assert

script:
  - go test -v ./...
